In [1]:
# Importing libraries for data manipulation and visualization
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Importing libraries for model building and evaluation
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier, VotingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Importing XGBoost
from xgboost import XGBClassifier

# Importing Label Encoder
from sklearn.preprocessing import LabelEncoder

# Load the Iris dataset
url = "Iris.csv"  # Provide the correct path where the dataset is located
iris_data = pd.read_csv(url)

# Display the first few rows of the dataset
iris_data.head()

# Check for missing values
iris_data.isnull().sum()

# Label encode the target variable (Species)
le = LabelEncoder()
iris_data['Species'] = le.fit_transform(iris_data['Species'])
# Check the encoding
iris_data['Species'].unique()

# Split the data into features (X) and target (y)
X = iris_data.drop('Species', axis=1)
y = iris_data['Species']

# Perform an 80/20 split for training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Initialize and train AdaBoost Classifier
ada_model = AdaBoostClassifier(n_estimators=100, random_state=42)
ada_model.fit(X_train, y_train)
# Predict on the test data
y_pred_ada = ada_model.predict(X_test)

# Initialize and train Gradient Boosting Classifier
gb_model = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb_model.fit(X_train, y_train)
# Predict on the test data
y_pred_gb = gb_model.predict(X_test)

# Initialize and train XGBoost Classifier
xgb_model = XGBClassifier(n_estimators=100, use_label_encoder=False, eval_metric='mlogloss', random_state=42)
xgb_model.fit(X_train, y_train)
# Predict on the test data
y_pred_xgb = xgb_model.predict(X_test)

# Evaluate AdaBoost Classifier
ada_accuracy = accuracy_score(y_test, y_pred_ada)
ada_report = classification_report(y_test, y_pred_ada)
ada_cm = confusion_matrix(y_test, y_pred_ada)
print(f"AdaBoost Accuracy: {ada_accuracy:.2f}")
print("AdaBoost Classification Report:\n", ada_report)
print("AdaBoost Confusion Matrix:\n", ada_cm)

# Evaluate Gradient Boosting Classifier
gb_accuracy = accuracy_score(y_test, y_pred_gb)
gb_report = classification_report(y_test, y_pred_gb)
gb_cm = confusion_matrix(y_test, y_pred_gb)
print(f"Gradient Boosting Accuracy: {gb_accuracy:.2f}")
print("Gradient Boosting Classification Report:\n", gb_report)
print("Gradient Boosting Confusion Matrix:\n", gb_cm)

# Evaluate XGBoost Classifier
xgb_accuracy = accuracy_score(y_test, y_pred_xgb)
xgb_report = classification_report(y_test, y_pred_xgb)
xgb_cm = confusion_matrix(y_test, y_pred_xgb)
print(f"XGBoost Accuracy: {xgb_accuracy:.2f}")
print("XGBoost Classification Report:\n", xgb_report)
print("XGBoost Confusion Matrix:\n", xgb_cm)

# Compare the accuracy scores of the three models
print(f"AdaBoost Accuracy: {ada_accuracy:.2f}")
print(f"Gradient Boosting Accuracy: {gb_accuracy:.2f}")
print(f"XGBoost Accuracy: {xgb_accuracy:.2f}")

C:\Users\AYUSHI CHOUGULE\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
C:\Users\AYUSHI CHOUGULE\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\core.py:158: UserWarning: [01:41:30] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


AdaBoost Accuracy: 1.00
AdaBoost Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

AdaBoost Confusion Matrix:
 [[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]
Gradient Boosting Accuracy: 1.00
Gradient Boosting Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Gradient Boosting Confusion Matrix:
 [[10